[tools]
neovim = "latest"
eza = "latest"
ghq = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
tree-sitter = "latest"
node = "latest"
lua-language-server = "latest"
"aqua:fzf" = "latest"
bat = "latest"
starship = "latest"
fd = "latest"
uv = "latest"
yazi = "latest"

[settings]
experimental = true
